import React from 'react'
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faBolt } from '@fortawesome/free-solid-svg-icons';
import Head from 'next/head'


export default function Home() {
  return (
    <>  
      <Head>
        <title>Biodigestor</title>
        <meta name="description" content="Generated by create next app" />
        {/* <FontAwesomeIcon color="#2937f0" icon={faBolt} /> */}
        <link rel="icon" href="/eletronic.ico" />
        
      </Head>
    </>

  )
}
